config/routes.rb
SnupyAgain::Application.routes.draw do
	
	resources :reports do
		member do
			get 'download'
		end
	end
	Report.subclasses.each do |k|
		resources k.name.underscore.pluralize, :controller => 'reports'
	end
	
	
	resources :entity_groups do
		collection do
			get 'batch_create'
			post 'batch_create'
			post 'show_dataset_summary'
			post 'assign_entity'
		end
	end
	
	resources :entities do
		collection do
			post 'assign_specimen_probe'
			post 'assign_entity_group'
			post 'assign_tags'
		end
		member do
			post 'show'
		end
	end
	
	resources :specimen_probes do
		collection do
			post 'assign_sample'
			post 'assign_entity'
			post 'assign_tags'
		end
	end
	
	resources :tags
	
	match 'long_jobs/clear_cache' => 'long_jobs#clear_cache', :as => "long_jobs_clear_cache", :via => "delete"
	match 'long_jobs/list' => 'long_jobs#list', :via => "get"
	match 'long_jobs/statistics' => 'long_jobs#statistics', :via => "get"
	match 'long_jobs/statistics' => 'long_jobs#statistics', :via => "post"
	match "long_jobs/:id/status" => 'long_jobs#status', :as => "long_job_status", :via => "get"
	match 'long_jobs/:id' => 'long_jobs#result', :as => "long_job_result", :via => "get"
	match 'long_jobs/:id/result' => 'long_jobs#result', :via => "get"
	match 'long_jobs/:id/kill' => 'long_jobs#destroy', :as => "long_job_kill", :via => "delete"
	match 'long_jobs' => 'long_jobs#index', :via => "get"
	
	
	
	resources :users do
		member do
			get 'longtask'
		end
		collection do
			get 'access_control_list'
		end
	end
	
	get "api", to: "home#api", as: "api"
	post "api", to: "home#api", as: "api"
	get "api_form", to: "home#api_form", as: "api_form"
	post "api_form", to: "home#api_form", as: "api_form"
	
	get "home/index"
	
	get "home/cookies"
	
	get "home/about"
	
	get "home/help"
	
	get "home/citation"
	
	get "home/aqua"
	get "home/show_log"
	post "home/show_log_details"
	post "home/destroy_log"
	
	get "aqua/query_collection/:qklass/:qname", to: "aqua#query_collection", as: "aqua_query_collection"
	get "aqua/query_details/:variation_id", to: "aqua#query_details", as: "aqua_query_details"
	post "aqua/query_details/:variation_id", to: "aqua#query_details", as: "aqua_query_details"
	
	get "tools/ppi_network"
	post "tools/ppi_network"
	get "tools/gene_details"
	post "tools/gene_details"
	
	resources :institutions, :generic_lists, :generic_gene_lists, :generic_region_lists
	resources :sample_tags
	resources :samples do
		collection do
			put 'refreshstats'
			get 'claimable'
			get 'refreshindex'
			post 'mass_destroy'
			post 'force_reload'
			post 'sample_similarity'
			post 'assign_specimen'
			post 'gender_coefficient'
			post 'refresh_stats'
		end
		member do
			get 'detail'
			post 'detail'
			put 'collectstats'
		end
	end
	
	resources :experiments do
		collection do
			post 'details'
			post 'more_details'
			get 'details'
			get 'more_details'
			post 'interactions'
			post 'interaction_details'
			post 'attribute_matrix'
			post 'panel_to_subject_matrix'
			post 'save_resultset'
		end
		member do
			get 'aqua'
			post 'aqua'
			get 'query_generator'
			post 'query_generator'
			get 'query', to: redirect('/experiments/%{id}/aqua')
		end
	end
	get 'experiments/aqua_meta/:user/:organism', controller: :experiments, action: :aqua_meta, as: :aqua_meta #=> "experiments#aqua_meta"
	
	get '/projects', to: redirect('/experiments')
	get '/projects/:id', to: redirect('/experiments/%{id}')
	
	resources :vcf_files do
		member do
			get 'annotate'
			get 'aqua_annotate'
			get 'download'
			post 'aqua_annotate_single'
		end
		collection do
			get 'batch_submit'
			post 'batch_submit'
			post 'create_sample_sheet'
			post 'download_sample_sheet'
			post 'assign_tags'
			post 'baf_plot'
			post 'mass_destroy'
			get 'baf_plot'
			get 'download_sample_sheet'
			get 'refreshindex'
		end
	end
	resources :vcf_file_varscans, :controller => "vcf_files", :type => "VcfFileVarscan"
	resources :vcf_file_excavators, :controller => "vcf_files", :type => "VcfFileExcavator"
	
	
	
	
	
	
	
	
	
	root :to => 'home#index'
	AquaRouter.load_aqua_routes

end

app/models/institution.rb
# == Description
# An Institution has many Experiments and VcfFiles. It is used to group samples and restrict access
# when using results from other samples in the experiment query.
# == Attributes
# [contact] Institution contact
# [email] E-Mail adress to lookup
# [name] Name
# [phone] Phone number, not checked if valid number
class Institution < ActiveRecord::Base
	has_many :experiments, dependent: :destroy
	has_many :vcf_files, dependent: :nullify
	# has_many :users, through: :experiments, inverse_of: :institutions
	# has_and_belongs_to_many :users, join_table: :institution_has_users
	
	# has_many :samples, through: :vcf_files, uniq: true, inverse_of: :institution

	has_many :affiliations, inverse_of: :institution, dependent: :destroy
	has_many :users, through: :affiliations

	# has_and_belongs_to_many :entity_groups, join_table: :institution_has_entity_groups
	has_many :entity_groups
	has_many :entities, class_name: "Entity", through: :entity_groups
	has_many :specimen_probes, through: :entities
	has_many :samples, through: :specimen_probes

	attr_accessible :contact, :email, :name, :phone

	before_destroy :destroy_has_and_belongs_to_many_relations
	def destroy_has_and_belongs_to_many_relations
		self.users = []
		self.entity_groups = []
	end

	def roles(user = nil)
		if user.nil? then
			ret = Hash.new([])
			users.each do |u|
				ret[u] = roles(u)
			end
		return ret
		else
			aff = affiliations.where("user_id" => user.id).first
		return [] if aff.nil?
		return aff.roles.values
		end
	end

end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
	before_filter :admin_required, :only => [ :new, :edit, :create, :delete, :destroy, :update ]
  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @institutions }
    end
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
    @institution = Institution.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @institution }
    end
  end

  # GET /institutions/new
  # GET /institutions/new.json
  def new
    @institution = Institution.new
		@users = User.all
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @institution }
    end
  end

  # GET /institutions/1/edit
  def edit
    @institution = Institution.find(params[:id])
    @users = User.all
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(params[:institution])
		
		respond_to do |format|
      if @institution.save
      	#@institution.users = User.find_all_by_id(params[:users])
      	(params[:user] || []).each do |uid, roles|
      		Affiliation.create_from_params(User.find(uid), {@institution.id => roles})
      	end
        format.html { redirect_to @institution, notice: 'Institution was successfully created.' }
        format.json { render json: @institution, status: :created, location: @institution }
      else
        format.html { render action: "new" }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /institutions/1
  # PUT /institutions/1.json
  def update
    @institution = Institution.find(params[:id])
		#@institution.users = User.find_all_by_id(params[:users])
		previous_affiliations = @institution.affiliation_ids
    (params[:user] || []).each do |uid, roles|
  		Affiliation.create_from_params(User.find(uid), {@institution.id => roles})
  	end
  	Affiliation.where(id: previous_affiliations).destroy_all if previous_affiliations.size > 0
    respond_to do |format|
      if @institution.update_attributes(params[:institution])
        format.html { redirect_to @institution, notice: 'Institution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution = Institution.find(params[:id])
    @institution.destroy

    respond_to do |format|
      format.html { redirect_to institutions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/institutions_helper.rb
# == Description
# Helper Module
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= form_for(@institution) do |f| %>
<% if @institution.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@institution.errors.count, "error") %> prohibited this institution from being saved:</h2>
	
		<ul>
			<% @institution.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
			<% end %>
		</ul>
	</div>
<% end %>
	
	<div class="field">
		<%= f.label :name %>
		<br />
		<%= f.text_field :name %>
	</div>
	
	<div class="field">
		<%= f.label :contact %>
		<br />
		<%= f.text_field :contact %>
	</div>
	
	<div class="field">
		<%= f.label :email %>
		<br />
		<%= f.text_field :email %>
	</div>
	
	<div class="field">
		<%= f.label :phone %>
		<br />
		<%= f.text_field :phone %>
	</div>

  <div class="field">
		<%=render_table(
								(@users), 
								title: "",
								id: "users",
								selected: @institution.user_ids,
								selectbox: false,
								columns: %w(name contact) + Affiliation.roles.values.map{|r| r.humanize} + %w(email phone Show)
								){|rec, user|
									Affiliation.roles.values.each do |role|
										rec[role.humanize] = check_box_tag "user[#{rec[:id]}][]", role, @institution.roles(user).include?(role)
									end
									rec
								}
		%>
  </div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/institutions/_help_edit.html.erb
<%= render partial: "#{params[:controller]}/help_new" %>

app/views/institutions/_help_show.html.erb
<%= render partial: "#{params[:controller]}/help_new" %>

app/views/institutions/edit.html.erb
<h1>Editing institution</h1>

<%= render 'form' %>

<%= link_to 'Show', @institution %> 
<%= link_to 'Back', institutions_path %>

app/views/institutions/index.html.erb
<h1>Institutions</h1>

<%= render_table(@institutions,
								title: "",
								id: "institutions",
								selectbox: false,
								css: {width: "800px"},
								columns: %w(name contact email phone affiliations),
								column_order: %w(name contact email phone affiliations Show)
								){|rec, institution|
									rec["affiliations"] = institution.roles.map{|user, roles|
										link_to "#{user.name}(#{roles.join(', ')})", user_path(user)
									}.join(" | ")
									rec["Edit"] = link_to 'Edit', edit_institution_path(institution)
									rec["Destroy"] = link_to 'Destroy', institution, method: :delete, data: { confirm: 'Are you sure?' } 
									rec	
								}
%>

<br />

<%= link_to 'New Institution', new_institution_path %>

app/views/institutions/new.html.erb
<h1>New institution</h1>

<%= render 'form' %>

<%= link_to 'Back', institutions_path %>

app/views/institutions/show.html.erb
<h2>Institution <%= @institution.name %> </h2>

<p>
  <b>Name: </b>
  <%= @institution.name %>
</p>

<p>
  <b>Contact: </b>
  <%= @institution.contact %>
</p>

<p>
  <b>E-Mail </b>
  <%= @institution.email %>
</p>

<p>
  <b>Phone: </b>
  <%= @institution.phone %>
</p>

<p>
  <b>Users:</b>
  <%= render partial: "users/list", locals: {users: @institution.users,  compact: true, selectbox: false}%>
</p>

<p>
	<%=render_table @institution.vcf_files.all(select: %w(id name filename md5checksum sample_names status contact created_at updated_at)),
									selectbox: false,
									title: "Vcf Files",
									columns:      %w(name filename sample_names status contact md5checksum created_at updated_at) ,
									column_order: %w(name filename sample_names status contact md5checksum created_at updated_at)
	%>
</p>



<%= link_to 'Edit', edit_institution_path(@institution) %> 
<%= link_to 'Back', institutions_path %>