config/routes.rb
SnupyAgain::Application.routes.draw do
	
	resources :reports do
		member do
			get 'download'
		end
	end
	Report.subclasses.each do |k|
		resources k.name.underscore.pluralize, :controller => 'reports'
	end
	
	
	resources :entity_groups do
		collection do
			get 'batch_create'
			post 'batch_create'
			post 'show_dataset_summary'
			post 'assign_entity'
		end
	end
	
	resources :entities do
		collection do
			post 'assign_specimen_probe'
			post 'assign_entity_group'
			post 'assign_tags'
		end
		member do
			post 'show'
		end
	end
	
	resources :specimen_probes do
		collection do
			post 'assign_sample'
			post 'assign_entity'
			post 'assign_tags'
		end
	end
	
	resources :tags
	
	match 'long_jobs/clear_cache' => 'long_jobs#clear_cache', :as => "long_jobs_clear_cache", :via => "delete"
	match 'long_jobs/list' => 'long_jobs#list', :via => "get"
	match 'long_jobs/statistics' => 'long_jobs#statistics', :via => "get"
	match 'long_jobs/statistics' => 'long_jobs#statistics', :via => "post"
	match "long_jobs/:id/status" => 'long_jobs#status', :as => "long_job_status", :via => "get"
	match 'long_jobs/:id' => 'long_jobs#result', :as => "long_job_result", :via => "get"
	match 'long_jobs/:id/result' => 'long_jobs#result', :via => "get"
	match 'long_jobs/:id/kill' => 'long_jobs#destroy', :as => "long_job_kill", :via => "delete"
	match 'long_jobs' => 'long_jobs#index', :via => "get"
	
	
	
	resources :users do
		member do
			get 'longtask'
		end
		collection do
			get 'access_control_list'
		end
	end
	
	get "api", to: "home#api", as: "api"
	post "api", to: "home#api", as: "api"
	get "api_form", to: "home#api_form", as: "api_form"
	post "api_form", to: "home#api_form", as: "api_form"
	
	get "home/index"
	
	get "home/cookies"
	
	get "home/about"
	
	get "home/help"
	
	get "home/citation"
	
	get "home/aqua"
	get "home/show_log"
	post "home/show_log_details"
	post "home/destroy_log"
	
	get "aqua/query_collection/:qklass/:qname", to: "aqua#query_collection", as: "aqua_query_collection"
	get "aqua/query_details/:variation_id", to: "aqua#query_details", as: "aqua_query_details"
	post "aqua/query_details/:variation_id", to: "aqua#query_details", as: "aqua_query_details"
	
	get "tools/ppi_network"
	post "tools/ppi_network"
	get "tools/gene_details"
	post "tools/gene_details"
	
	resources :institutions, :generic_lists, :generic_gene_lists, :generic_region_lists
	resources :sample_tags
	resources :samples do
		collection do
			put 'refreshstats'
			get 'claimable'
			get 'refreshindex'
			post 'mass_destroy'
			post 'force_reload'
			post 'sample_similarity'
			post 'assign_specimen'
			post 'gender_coefficient'
			post 'refresh_stats'
		end
		member do
			get 'detail'
			post 'detail'
			put 'collectstats'
		end
	end
	
	resources :experiments do
		collection do
			post 'details'
			post 'more_details'
			get 'details'
			get 'more_details'
			post 'interactions'
			post 'interaction_details'
			post 'attribute_matrix'
			post 'panel_to_subject_matrix'
			post 'save_resultset'
		end
		member do
			get 'aqua'
			post 'aqua'
			get 'query_generator'
			post 'query_generator'
			get 'query', to: redirect('/experiments/%{id}/aqua')
		end
	end
	get 'experiments/aqua_meta/:user/:organism', controller: :experiments, action: :aqua_meta, as: :aqua_meta #=> "experiments#aqua_meta"
	
	get '/projects', to: redirect('/experiments')
	get '/projects/:id', to: redirect('/experiments/%{id}')
	
	resources :vcf_files do
		member do
			get 'annotate'
			get 'aqua_annotate'
			get 'download'
			post 'aqua_annotate_single'
		end
		collection do
			get 'batch_submit'
			post 'batch_submit'
			post 'create_sample_sheet'
			post 'download_sample_sheet'
			post 'assign_tags'
			post 'baf_plot'
			post 'mass_destroy'
			get 'baf_plot'
			get 'download_sample_sheet'
			get 'refreshindex'
		end
	end
	resources :vcf_file_varscans, :controller => "vcf_files", :type => "VcfFileVarscan"
	resources :vcf_file_excavators, :controller => "vcf_files", :type => "VcfFileExcavator"
	
	
	
	
	
	
	
	
	
	root :to => 'home#index'
	AquaRouter.load_aqua_routes

end

app/models/user.rb
# == Description
# A User has access to different Experiments that he can create himself. 
# The User-Authentification is done through the HTTP-Authentification, 
# so you have to setup .htaccess access to you website. The default User is
# development who also has admin priviledges and can create new users.
# TODO: Integrate a better User management.
# == Attributes
# [email] e-mail
# [full_name] full name
# [is_admin] TRUE/FALSE if the user has admin priviledges. This lets him manage other users, institutions and datasets.
# [name] username (short form)
class User < ActiveRecord::Base
	has_and_belongs_to_many :experiments, join_table: :experiment_has_user
	# with the new sample annotation schema this relationship is to be ignored
	has_and_belongs_to_many :samples, join_table: :sample_has_users
	has_and_belongs_to_many :generic_lists, join_table: :generic_list_has_users
	# has_and_belongs_to_many :institutions, join_table: :institution_has_users
	has_many :affiliations, dependent: :destroy 
	has_many :institutions, through: :affiliations
	has_many :collegues, through: :institutions, class_name: "User", source: :users
	# has_many :entity_groups, through: :institutions
	# we link each user explicitly with an entity group.
	# This way we can share a group with someone from another institution without him being able to modify it
	has_and_belongs_to_many :entity_groups, join_table: :user_has_entity_groups
	has_many :entities, through: :entity_groups
	has_many :specimen_probes, through: :entities, class_name: "SpecimenProbe"
	# has_many :samples, through: :specimen_probes
	
	# has_many :vcf_files, readonly: true, through: :samples 
	# users should only be able to access VCF data if the are admin or have manager roles in the instituion the vcf belongs to.
	has_many :vcf_files, readonly: true, through: :institutions, :conditions => Proc.new { %Q{
		roles LIKE '%_manager%' OR #{id} IN (
			SELECT id FROM users WHERE is_admin = 1
		)
	}}
	
	has_many :variations, through: :samples, inverse_of: :users
	has_many :variation_calls, through: :samples, inverse_of: :users
	
	has_one :api_key

	has_many :long_jobs, through: :experiments, :conditions => Proc.new { %Q{long_jobs.user = '#{name}'}}
	
	has_many :reports, dependent: :destroy
	attr_accessible :email, :full_name, :is_admin, :name
	
	validates :name, presence: true, uniqueness: true
	before_destroy :destroy_has_and_belongs_to_many_relations
	
	def destroy_has_and_belongs_to_many_relations
		# samples are now linked to a user via their entity groups. 
		# self.samples = []
		self.experiments = []
		self.generic_lists = []
		self.institutions = []
	end
	
	# returns a ActiveRecord::Relation which can be used to query the data
	def accessible_models(mdl, required_roles, include_direct_access = true)
		required_roles = Hash[required_roles.map{|x| [x, true]}]
		# check if association to institution and affiliations exists
		instassoc = (Aqua.find_association(mdl, :institution) || Aqua.find_association(mdl, :institutions))
		raise "accessible model requires association to institution" if instassoc.nil?
		# affiassoc = Aqua.find_association(mdl, :affiliations)
		
		mdltable = mdl.table_name
		assoc = Aqua.find_association(self.class, mdl)
		raise "Association not found" if assoc.nil?
		idsmethod = (assoc.name.to_s.singularize + "_ids").to_sym
		raise "Association derived access not found but required" if !respond_to?(idsmethod) && include_direct_access
		if is_admin
			ret = mdl.scoped #.joins(:institution)#.includes(:institution).where("1 = 1")
		else
			insts = roles.select{|institution, roles|
				roles.any?{|r| required_roles[r]}
			}
			if insts.nil? then # user does not meet the requirements in any institution
				return mdl.where("1 = 0")
			else
				insts = insts.keys
			end
			direct_accessible_ids = []
			direct_accessible_ids = send(idsmethod) if include_direct_access
			cond = []
			# we allow access to samples either by institution or by explicit permission - so a user doesnt have to be part of an institution, if he is granted direct access
			cond << "institutions.id IN (#{insts.map(&:id).join(",")})" if insts.size > 0
			cond << "#{mdltable}.#{mdl.primary_key} IN (#{direct_accessible_ids.join(",")})" if direct_accessible_ids.size > 0
			if cond.size > 0 
				if (Aqua.find_association(mdl, :institution)) then
					retids = mdl.joins(:institution).where(cond.join(" OR ")).pluck("#{mdltable}.#{mdl.primary_key}")
				elsif Aqua.find_association(mdl, :institutions) then
					retids = mdl.joins(:institutions).where(cond.join(" OR ")).pluck("#{mdltable}.#{mdl.primary_key}")
				else
					raise "Association between #{mdl} and Institution not found. Make sure an 'institution' or 'institutions' association is defined"
				end
				ret = mdl.where("#{mdltable}.#{mdl.primary_key}" => retids.uniq)
							# .includes(:institution) # when there is no includes the returned records will be read only
			else
				ret = mdl.where("1 = 0") # this is the best way to have a good empty relation. Rails 4 provides .none which would be nicer to use.
			end
		end
		ret
	end
	
	def can_see?(ids, mdl = (ids.is_a?(Array))?(ids.first.class):(ids.class))
		able_to?(:view, mdl, ids)
	end
	
	def can_review?(ids, mdl = (ids.is_a?(Array))?(ids.first.class):(ids.class))
		able_to?(:review, mdl, ids)
	end
	
	def can_edit?(ids, mdl = (ids.is_a?(Array))?(ids.first.class):(ids.class))
		able_to?(:edit, mdl, ids)
	end

	def owns?(ids, mdl = (ids.is_a?(Array))?(ids.first.class):(ids.class))
		able_to?(:own, mdl, ids)
	end
	
	def able_to?(action, mdl, ids = nil)
		action = action.to_s.downcase.to_sym
		if action == :visible or action == :see or action == :view then
			canids = visible(mdl).pluck("#{mdl.table_name}.#{mdl.primary_key}").sort
		elsif action == :editable or action == :edit or action == :modify or action == :manage then
			canids = editable(mdl).pluck("#{mdl.table_name}.#{mdl.primary_key}").sort
		elsif action == :review or action == :filter then
			canids = reviewable(mdl).pluck("#{mdl.table_name}.#{mdl.primary_key}").sort
		elsif action == :owns or action == :belongs or action == :own then
			canids = owned(mdl).pluck("#{mdl.table_name}.#{mdl.primary_key}").sort
		end
		return canids if ids.nil?
		ids = [ids] unless ids.is_a?(Array)
		ids = ids.map{|obj| (obj.is_a?(ActiveRecord::Base))?(obj.id):(obj)}
		ids.all?{|id| canids.include?(id)}
	end
	
	# gives you objects that are directly associated to you
	# or which you can access indirectly because you have access to it
	def owned(mdl)
		accessible_models(mdl, [], true)
	end
	
	# visible and reviewable are equal now that we have an advanced query schema
	def visible(mdl)
		# accessible_models(mdl, ["user", "research_manager", "data_manager"], true)
		accessible_models(mdl, ["user", "research_manager", "data_manager"], true)
	end
	
	# to view an object you have to be either a data or a research manager or be linked with it directly
	def reviewable(mdl)
		accessible_models(mdl, ["research_manager", "data_manager"], true)
		# visible(mdl)
	end
	
	# just the fact that you are linked as a user of an object doesnt give you the right to edit it
	# well it kind of should, because what is the point then?
	# Only data managers should be able to modify datasets.
	# If a direct association is available the datasets through the direct association need to be associated to the same
	# instition as the user. Otherwise it allows external users to edit a dataset.
	def editable(mdl)
		ret = accessible_models(mdl, ["data_manager"], true)
		if (Aqua.find_association(mdl, :institution)) then
			ret = ret.joins(:institution).where("institutions.id" => self.institutions)
		else Aqua.find_association(mdl, :institutions)
		ret = ret.joins(:institutions).where("institutions.id" => self.institutions)
		end
		ret
	end
	
	def is_admin?()
		read_attribute(:is_admin)
	end
	
	def roles(institution = nil)
		@_institution_cache = nil
		@_institution_cache = {} if @_institution_cache.nil? # using a cache might be not such a good idea at some point...
		return @_institution_cache[institution] unless @_institution_cache[institution].nil? 
		if institution.nil? then
			ret = Hash.new()
			ret.default = []
			institutions.each do |i|
				ret[i] = roles(i)
			end
			return ret
		else
			# aff = affiliations.where(institution_id: institution.id).first
			aff = affiliations.select{|a| a.institution_id == institution.id}.first
			return [] if aff.nil?
			ret = aff.roles.values
			@_institution_cache[institution] = ret
			return ret
		end
	end
	
	def is_data_manager_at?(institution)
		return false if institution.nil?
		# User.joins(:affiliations).where("affiliations.institution_id" => institution.id)
		roles(institution).include?("data_manager")
	end
	
	def is_research_manager_at?(institution)
		return false if institution.nil?
		roles(institution).include?("research_manager")
	end
	
	def is_user_at?(institution)
		return false if institution.nil?
		roles(institution).include?("user")
	end
	
	def is_data_manager?()
		roles.any?{|inst, roles| roles.include?("data_manager")} || is_admin?
	end
	
	def is_research_manager?()
		roles.any?{|inst, roles| roles.include?("research_manager")}
	end
	
	def is_user?()
		roles.any?{|inst, roles| roles.include?("user")} || is_research_manager? || is_data_manager?
	end
	
	def jobs
		LongJob.where("user = ? OR user = ?", self.name, self.full_name)
	end
	
	def has_api?
		return !self.api.nil?
	end
	
	# TODO Refactor this, so it is treated like samples are.
	def generic_gene_lists()
		return GenericGeneList.where(type: "GenericGeneList") if self.is_admin
		return generic_lists().where(type: "GenericGeneList")
	end
	
	def generic_region_lists()
		return GenericRegionList.where(type: "GenericRegionList") if self.is_admin
		return generic_lists().where(type: "GenericRegionList")
	end
	
end

app/helpers/samples_helper.rb
# == Description
# Helper Module
module SamplesHelper
end

app/views/samples/_baf_stats.html.erb
<%if defined? samples || defined? sample %>
	<h3>BAF Plot</h3>
	<%
		plotdata = {}
		entropies = []
	%>
	<%
		if defined? sample then
			sample = [sample] unless sample.is_a?(Array)
			samples = sample
		end
		samples.sort{|s1, s2| s1.nickname <=> s2.nickname}.each do |sample|
			next if !sample.name.downcase.index("mutect").nil? && samples.size > 1
			next if !sample.name.downcase.index("varscan").nil? && samples.size > 1
			next if !sample.name.downcase.index("somatic").nil? && samples.size > 1
			next if !sample.name.downcase.index("denovo").nil? && samples.size > 1
			next if !sample.name.downcase.index("relax").nil? && samples.size > 1
			bafs = sample.statistics.where(name: "BAF")
			next if bafs.size == 0
			bafs.each do |bafstat|
				baf_dist = YAML.load(bafstat.value)
				baf_dist_max = baf_dist.values.max
				baf_dist_max = 0.0000001 if baf_dist_max == 0 or baf_dist_max.nil?
				baf_dist_vals = (baf_dist.values.map{|x| x.to_f / baf_dist_max })
				baf_description = bafstat.name + "." + sample.name.gsub(/[ \/_,\-\\]/, ".") + "(ID##{sample.id})"
				plotdata[baf_description] = {
																			x: baf_dist.keys,
																			y: baf_dist_vals
																		}
				ent = get_entropy(baf_dist.values).to_s.to_f
				entropies << {
					id: sample.id,
					name: sample.name,
					entropy: ent
				}
			end
		end 
	%>
	
	<%= render partial: "statistics/series.html.erb", locals: {plotdata: plotdata}%>
	<%= render_table(entropies,
									 title: "BAF Entropies",
									 colors: {
											 entropy: Aqua.create_color_gradient([0.0, 3.5, 4.5, 5.5, 6.0], %w(salmon lightyellow palegreen lightsalmon salmon))
									 }
			)%>
	
<%end%>

app/views/samples/_collectstats.js.erb
$('#<%=params[:container] %>').html("Collection of statistics started");
refreshJobList();

app/views/samples/_help_edit.html.erb
<%= render partial: "#{params[:controller]}/help_new" %>

app/views/samples/_help_show.html.erb
<%= render partial: "#{params[:controller]}/help_new" %>

app/views/samples/_similarity.html.erb
<h2>Sample Overlaps</h2>
<p>
	<%=render_table(simmat, 
									title: "Unsorted #{measure} similarity",
									color: {
										#/^(?!name).*$/ => create_color_gradient([min,(min+max)/2, max], colors = ["salmon", "lightyellow", "palegreen"])
										# /^(?!name).*$/ => create_color_gradient([min,(min+max)/2, max], colors = ["white", "lightyellow", "palegreen"])
										/^(?!name).*$/ => create_color_gradient([min,max], colors = ["white", "salmon"])
										# /^(?!name).*$/ => create_color_gradient([min,(min+max)/2, max], colors = ["#ffeda0", "#feb24c", "#f03b20"]),
									}
									)
	%>
</p>

app/views/samples/create_from_sample_sheet.html.erb
<%=render_table(
	@result,
	id: "sample_sheet_result",
	title: "Sample Sheet Import Result",
	collapsecell: -1,
	basemodel: Sample,
	autolink_id: true,
	column_order: %w(sampleID name nickname specimen Show error notice patient vcf_file_id vcf_sample_name tags users job status),
	colors: {
		"error" => {
			/.+/ => "salmon"
		}
	}
){|rec, smpl|
	if rec[:id].to_s != "" then
		rec["Show"] = link_to 'Show', sample_path(rec[:id])
	else
		rec["Show"] = ""
	end
	rec
	}%>
<br />
<%= link_to 'Claim Sample', new_sample_path %>
<%= link_to 'All samples', samples_path %>

app/views/samples/edit.html.erb
<h1>Edit sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> 
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<h1>Samples</h1>
<% 
	actions = {}
	actions["Assign to specimen"] = assign_specimen_samples_path()
	actions["Similarity"] = sample_similarity_samples_path()
	actions["Gender Coefficient"] = gender_coefficient_samples_path()

	actions["Refresh Statistics"] = refresh_stats_samples_path() if current_user.is_data_manager?

	actions["Refresh Samples"] = force_reload_samples_path() if current_user.is_admin
	actions["Destroy Samples"] = mass_destroy_samples_path() if current_user.is_admin
%>
<%=render_table(@samples, 
								title: "#{params[:count] || @samples.size} most recently updated",
								selectbox: true,
								collapsecell: -1,
								record_color: {
									"Group/Entity/Specimen/Sample" => :factor
								},
								column_order: %w(SampleID Group/Entity/Specimen/Sample patient ^name nickname specimen_probe_id vcf_file_name vcf_sample_name tags sample_type gender experiments institution ignorefilter min_read_depth info_matches contact notes status .*),
								actions: actions
								){|rec, smpl|
	rec["SampleID"] = link_to "#{smpl.id}", sample_path(smpl)
	# rec[:edit] = link_to 'Edit', edit_sample_path(rec[:id])
	rec["Edit"] = ""
	rec["Edit"] = link_to smpl.name, edit_sample_path(smpl) if @my_samples.include?(smpl.id)
	rec[:destroy] = link_to 'Destroy', smpl, method: :delete, data: { confirm: 'Are you sure?' }
# 	rec[:vcf_file_id] = link_to "#{rec[:vcf_file_id]}", vcf_file_path(rec[:vcf_file_id])
	if rec[:vcf_file_id].to_s != "" then
		vcf_file = smpl.vcf_file_nodata #VcfFile.find(rec[:vcf_file_id].to_i, select: [:name]) 
		rec[:vcf_file_name] = link_to "#{vcf_file.name}", vcf_file_path(rec[:vcf_file_id])
	else
		rec[:vcf_file_name] = ""
	end
	rec[:experiments] = smpl.experiments.map{|exp| link_to exp.name, aqua_experiment_path(exp)}.join(", \n").html_safe
	if !smpl.institution.nil?
		rec[:institution] = link_to smpl.institution.name, sample_path(smpl.institution.id)
	else
		rec[:institution] = "No institution assigned"
	end
	rec[:tags] = smpl.tags_by_category.map{|category, tags| "#{category}: #{tags.map(&:value).join(";")}"}.join(", ")
	# rec["Group/Entity/Specimen/Sample"] = ([ smpl.entity_group, smpl.entity, smpl.specimen_probe].map{|x| (!x.nil?)?(x.name):("")} + [smpl.nickname]).join(" | ")
	rec["Group/Entity/Specimen/Sample"] = ([ smpl.entity_group, smpl.entity, smpl.specimen_probe].map{|x| (!x.nil?)?(x.name):("NA")} + [smpl.nickname])
	rec["Reports"] = link_to smpl.reports.count, reports_path(ids: smpl.report_ids)
	rec
}%>
<br />
<%= link_to 'Claim Sample', new_sample_path %>

<% if current_user.is_admin then %>
	<p>
		<h2>Statistics</h2>
		<%=render_table(@stat_collectors, 
										title: "",
										selectbox: false
										){|rec, smpl|
				rec["Calculate for all samples"] = "<div id='refreshall_stats_#{rec[:resource].hash}'>" + 
										(link_to rec[:resource], 
											refreshstats_samples_url(resource: rec[:resource], 
											container: "refreshall_stats_#{rec[:resource].hash}", 
											format: "js"
										), remote: true, data: { confirm: 'This will refresh the statistics for ALL samples. Are you sure?' } , method: "PUT") +
									"</div>"
			rec
		}%>
	</p>
<% end %>

app/views/samples/new.html.erb
<h1>Claim a sample</h1>
<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<h1><%=@sample.name%></h1>

<p>
	<%= link_to 'Edit', edit_sample_path(@sample) %> 
	<%= link_to 'Back', samples_path %>
</p>
<p>
	<%=render_table(@sample, 
									title: "Sample Info",
									selectbox: false,
									column_order: %w(name nickname patient status vcf_sample_name gender sample_type min_read_depth ignorefilter info_matches notes contact .*)
	
			)
	%>
</p>
<p style="width:30%;">
	<% if @sample.tags.size > 0 %>
		<%=render_table(@sample.tags, 
									title: "Tags",
									selectbox: false,
									columns: %w(category subcategory value description)
									)%>
	<% end %>
</p>

<p>
	<% if @sample.statistics.size > 0 %>
		<%=render_table(@sample.statistics, 
									title: "Sample Statistics",
									selectbox: false,
									columns: %w(name resource record_id type)
									){|rec, stat|
									rec["Refresh"] = "<div id='collect_stats_#{rec[:resource].hash}'>" + 
																	(link_to "Start", 
																		collectstats_sample_path(@sample, 
																		resource: rec[:resource], 
																		container: "collect_stats_#{rec[:resource].hash}", 
																		format: "js"
																	), remote: true , method: "PUT") +
																"</div>"
				rec
			}%>
	<% end %>
</p>

<p>
	<% if @missing_stat_collectors.size > 0 %>
		<% if @sample.ready_to_query? %>
			<%=render_table(@missing_stat_collectors, 
									title: "Other Available Sample Stats",
									selectbox: false
									) {|rec, stat|
									rec["(Re-)Calculate"] = "<div id='collect_stats_#{rec[:resource].hash}'>" + 
																	(link_to "Start", 
																		collectstats_sample_path(@sample, 
																		resource: rec[:resource], 
																		container: "collect_stats_#{rec[:resource].hash}", 
																		format: "js"
																	), remote: true , method: "PUT") +
																"</div>"
				rec
			}%>
		<% else %>
			<%=@missing_stat_collectors.size%> sample statistics cannot be calculate because this sample is not ready. Please check if variations are already added and if the sample is annotated adequatly.
		<% end %>
	<% end %>
</p>


<h3>Users</h3>
<%=render partial: "users/list", locals: {users: @sample.users, compact: true, selectbox: false}%>

<% if @sample.statistics.where(name: "BAF").size > 0 then %>
	<p>
			<%= render(partial: "baf_stats", locals: {samples: [@sample]}) %>
	</p>
<% end %>

<% if @sample.statistics.where(name: "SampleVariation").size > 0 then %>
	<p>
			<%= render(partial: "variation_stats", locals: {sample: @sample}) %>
	</p>
<% end %>

</p>
	<%= render_table(@sample.reports,
					 id:          "reports",
					 title:       "Reports",
					 columns: %w(name identifier filename created_at updated_at download),
					 select_type: :none){|rec, rep|
		rec[:name] = link_to rep.name, report_path(rep.id)
		rec["download"] = link_to rep.name, download_report_path(rep.id)
		rec
	} %>
<p>

<%= link_to 'Edit', edit_sample_path(@sample) %> 
<%= link_to 'Back', samples_path %>