config/routes.rb
SnupyAgain::Application.routes.draw do
	
	resources :reports do
		member do
			get 'download'
		end
	end
	Report.subclasses.each do |k|
		resources k.name.underscore.pluralize, :controller => 'reports'
	end
	
	
	resources :entity_groups do
		collection do
			get 'batch_create'
			post 'batch_create'
			post 'show_dataset_summary'
			post 'assign_entity'
		end
	end
	
	resources :entities do
		collection do
			post 'assign_specimen_probe'
			post 'assign_entity_group'
			post 'assign_tags'
		end
		member do
			post 'show'
		end
	end
	
	resources :specimen_probes do
		collection do
			post 'assign_sample'
			post 'assign_entity'
			post 'assign_tags'
		end
	end
	
	resources :tags
	
	match 'long_jobs/clear_cache' => 'long_jobs#clear_cache', :as => "long_jobs_clear_cache", :via => "delete"
	match 'long_jobs/list' => 'long_jobs#list', :via => "get"
	match 'long_jobs/statistics' => 'long_jobs#statistics', :via => "get"
	match 'long_jobs/statistics' => 'long_jobs#statistics', :via => "post"
	match "long_jobs/:id/status" => 'long_jobs#status', :as => "long_job_status", :via => "get"
	match 'long_jobs/:id' => 'long_jobs#result', :as => "long_job_result", :via => "get"
	match 'long_jobs/:id/result' => 'long_jobs#result', :via => "get"
	match 'long_jobs/:id/kill' => 'long_jobs#destroy', :as => "long_job_kill", :via => "delete"
	match 'long_jobs' => 'long_jobs#index', :via => "get"
	
	
	
	resources :users do
		member do
			get 'longtask'
		end
		collection do
			get 'access_control_list'
		end
	end
	
	get "api", to: "home#api", as: "api"
	post "api", to: "home#api", as: "api"
	get "api_form", to: "home#api_form", as: "api_form"
	post "api_form", to: "home#api_form", as: "api_form"
	
	get "home/index"
	
	get "home/cookies"
	
	get "home/about"
	
	get "home/help"
	
	get "home/citation"
	
	get "home/aqua"
	get "home/show_log"
	post "home/show_log_details"
	post "home/destroy_log"
	
	get "aqua/query_collection/:qklass/:qname", to: "aqua#query_collection", as: "aqua_query_collection"
	get "aqua/query_details/:variation_id", to: "aqua#query_details", as: "aqua_query_details"
	post "aqua/query_details/:variation_id", to: "aqua#query_details", as: "aqua_query_details"
	
	get "tools/ppi_network"
	post "tools/ppi_network"
	get "tools/gene_details"
	post "tools/gene_details"
	
	resources :institutions, :generic_lists, :generic_gene_lists, :generic_region_lists
	resources :sample_tags
	resources :samples do
		collection do
			put 'refreshstats'
			get 'claimable'
			get 'refreshindex'
			post 'mass_destroy'
			post 'force_reload'
			post 'sample_similarity'
			post 'assign_specimen'
			post 'gender_coefficient'
			post 'refresh_stats'
		end
		member do
			get 'detail'
			post 'detail'
			put 'collectstats'
		end
	end
	
	resources :experiments do
		collection do
			post 'details'
			post 'more_details'
			get 'details'
			get 'more_details'
			post 'interactions'
			post 'interaction_details'
			post 'attribute_matrix'
			post 'panel_to_subject_matrix'
			post 'save_resultset'
		end
		member do
			get 'aqua'
			post 'aqua'
			get 'query_generator'
			post 'query_generator'
			get 'query', to: redirect('/experiments/%{id}/aqua')
		end
	end
	get 'experiments/aqua_meta/:user/:organism', controller: :experiments, action: :aqua_meta, as: :aqua_meta #=> "experiments#aqua_meta"
	
	get '/projects', to: redirect('/experiments')
	get '/projects/:id', to: redirect('/experiments/%{id}')
	
	resources :vcf_files do
		member do
			get 'annotate'
			get 'aqua_annotate'
			get 'download'
			post 'aqua_annotate_single'
		end
		collection do
			get 'batch_submit'
			post 'batch_submit'
			post 'create_sample_sheet'
			post 'download_sample_sheet'
			post 'assign_tags'
			post 'baf_plot'
			post 'mass_destroy'
			get 'baf_plot'
			get 'download_sample_sheet'
			get 'refreshindex'
		end
	end
	resources :vcf_file_varscans, :controller => "vcf_files", :type => "VcfFileVarscan"
	resources :vcf_file_excavators, :controller => "vcf_files", :type => "VcfFileExcavator"
	
	
	
	
	
	
	
	
	
	root :to => 'home#index'
	AquaRouter.load_aqua_routes

end

app/controllers/home_controller.rb
##
# This class is used as a wrapper to show static pages.
# These pages can be changed, by changing the views.
class HomeController < ApplicationController
	
	before_filter(:only => [:api, :api_form]) { redirect_to root_path, alert: "You don't have permission to use the Query Interface." if current_user.api_key.nil? }
	
	include ApiHelper
	include ApplicationHelper
	
	def index
		@user = current_user
		#@vcf_files = @user.vcf_files
		#									.where(status: "DONE")
		#									.select(["vcf_files.id", "vcf_files.name", :sample_names, "vcf_files.contact"])
		#									.order('vcf_files.created_at DESC')
		#									.limit(64)
		#@incomplete_samples = @user.samples.reject(&:ready_to_query?)
		@experiments = @user.experiments.includes(:samples).order(:name)
		@data_overview = EntityGroup.dataset_summary(@user.owned(EntityGroup).order("entity_groups.updated_at DESC").limit(100).pluck(:id), false)
		@orphan_samples = current_user.visible(Sample).where(specimen_probe_id: nil).order("samples.updated_at DESC").limit(1000)
		@orphan_samples_total = current_user.visible(Sample).where(specimen_probe_id: nil).count
	end
	
	def about
	end
	
	def help
	end
	
	def citation
	end
	
	def aqua
		Aqua._reload() if Rails.env == "development"
		@annotations = Aqua.annotations
		@queries = Aqua.queries
		@aggregations = Aqua.aggregations
		@filters = []
		annot_order = Annotation.sort_by_requirements(@annotations.keys)
		@annotations = @annotations.map{|klass, config|
			{
				"Klass" => klass.name, 
				"Toolname" => config[:tool],
				"Name" => config[:name],
				"Execution Rank" => annot_order.index(klass),
				"Label" => config[:label], 
				"Input Format" => config[:input],
				"Output Format" => config[:output], 
				"Supported Organisms" => config[:organism].map(&:name).join(", "),
				"Supported Mutation types" => config[:supports].join(", "),
				"Required Models" => config[:model].map{|m|
					if m.is_a?(Array) # config[:model] can be an Array or a Hash - but when it is a Hash, then m will be [mode, [relations]]
						if m[1].is_a?(Array) then
							"#{m[0]} => <br>    #{m[1].map(&:name).join(" & ")}"
						else
							m.map{|ma| ma.name}.join(" & ")
						end
					else
						m.name
					end
				}.join("<br>").html_safe,
				"Satisfied?" => klass.satisfied?,
				# "Ready?" => klass.ready?,
				"Ready?" => klass.ready_machines.join(", "),
				"Required Annotations" => klass.get_requirements.map(&:name),
				"Required annotations available?" => klass.meets_all_requirements?,
				"Type" => klass.type,
				"Vcf Files" => ["OK", "PENDING", "INCOMPLETE", "REVOKED", "FAIL", "NOTAPPLICABLE"].map{|state| "#{state}: #{(klass.vcf_files(state) || []).size}"}.join(" | ")
			}
		}
		
		@queries = @queries.map{|type, klass2query|
			klass2query.map do |qklass, queries|
				queries.map do |qname, config|
					filters = qklass.filters[qname]
					filters = [] if filters.nil?
					filters.each do |f|
						collector_output = "METHOD NOT FOUND"
						if f.respond_to?(f.collection_method) then
							begin
								if f.public_methods(false).include?(f.collection_method.to_sym) then
									collector_output = f.send(f.collection_method, {}).first(64).map{|rec| 
										rec.pretty_inspect.gsub("  ", "&nbsp;&nbsp;").gsub("<", "&lt;").gsub(">", "&gt;").html_safe
									}.join("<br>").html_safe
									collector_output = "EMPTY" if collector_output == ""
								else
									collector_output = "" # not implemented for this filter.
								end
							rescue
								collector_output = "Could not determine automatically."
							end
						end
						fmethod = f.filter_method
						if fmethod.is_a?(Proc) then
							fmethod = "##{File.basename(fmethod.source_location.first)}:#{fmethod.source_location[1]}(#{fmethod.parameters.map{|x| x[1].to_s}.join(", ")})"
						end
						@filters << {
							"Klass" => f.class.name, 
							"Name" => f.name,
							"Label" => f.label,
							"Method" => fmethod,
							"Checked?" => f.checked,
							"Organisms" => f.organism.map(&:name).join(", "),
							"Applicable?" => f.applicable?, # f.organism.map{|o| "#{o.name}(#{f.applicable?(o.id)})"}.join(", "),
							"Requirements" => f.requirements,
							"Query" => "#{qklass.name}:#{qname}",
							"Collector" => f.collection_method.to_s,
							"Collector Output" => collector_output,
							"fkey" => f.fkey
						}
					end
					{
						"Klass" => qklass.name, 
						"Query" => qname,
						"Type"  => type,
						"Label" => config[:label],
						"Default" => config[:default],
						"Combine default" => config[:combine],
						"Tooltip" => config[:tooltip],
						"Supported Organisms" => config[:organism].map(&:name).join(", "),
						"Priority" => config[:priority],
						"Filter" => filters.map{|f|
							#f.class.name + "(#{f.name.to_s})[#{f.applicable?}]"
							f.fkey + "[#{f.applicable?}]"
						}.join("<br>").html_safe,
						"No. Filter" => filters.size,
						"qkey" => qklass.qkey(qname)
					}
				end
			end
		}.flatten
		
		@aggregations = @aggregations.map{|aklass, aggregations|
			aggregations.map do |aname, config|
				{
					"Klass" => aklass.name,
					"Name" => aname,
					"Applicable?" => aklass.applicable?(aname),
					"akey" => aklass.akey(aname)
				}.merge(config)
			end
		}.flatten
		
	end

	def show_log
		#@query_log = AquaQueryProcess.get_query_log(true)
		@query_log = EventLog.order("created_at DESC")
		@query_log = filter_collection @query_log, [:name, :identifier, :category], 100
		respond_to do |format|
			format.html # index.html.erb
			format.json {render json: @query_log}
		end
	end
	
	def show_log_details
		if params[:ids].size > 0
			@logs = EventLog.find(params[:ids]).map{|e|
				ret = (e.data || {}).dup
				ret = {data: ret} unless ret.is_a?(Hash)
				ret = {
						"event.name" => e.name,
						"event.identifier" => e.identifier,
						"event.duration" => e.duration,
						"event.error" => e.error,
						"event.category" => e.category
				}.merge(ret)
				ret
			}
			
			render_table(@logs,
			             title: "Log Data",
			             columns: (@logs.map(&:keys) || []).flatten.uniq
			             )
		else
			render text: "No entries selected", status: 500
		end
	end
	
	def destroy_log
		require_params  = {
			ids:                 params[:ids],
			"Are you sure?" => ["no", "yes"]
		}
		if determine_missing_params(require_params).size > 0 then
			render_table_details_params(require_params)
		else
			if (params["Are you sure?"] == "yes") then
				begin
					EventLog.where(id: params[:ids]).destroy_all
					render text: "[Success] Deleted #{params["ids"].size} records"
				rescue
					render text: "[Error] Could not delete log entries", status: 500
				end
			else
				render text: "[Abort] not doing anything."
			end
		end
		
		
	end

end

app/helpers/home_helper.rb
# == Description
# Helper Module
module HomeHelper
end

app/views/home/_collection_filter.html.erb
<%=form_tag request.path, method: "GET" do %>
	<% if filter_names.map{|f| (params[:_filter] || {})[f]}.reject{|x| x.to_s == ""}.size > 0 then %>
		<div style="margin-left: 5px; font-size: 1.17em; font-weight: bold; display: block; border-bottom: 1px dashed black; width: 100%;">Showing <%="#{params[:count]}"%> results filtered by: 
		<%= filter_names.select{|f| (params[:_filter] || {})[f].to_s != ""}.map {|f|
			"#{f}: #{params[:_filter][f]}"
		}.join(" AND ") %>
		</div>
	<% end %>
	<div class="col_container">
		<div class="col actions">
			<%= submit_tag "Filter list", {style: "font-size: 1.17em; font-weight: bold; padding: 3px 32px 3px 32px;"} %>
		</div>
		<div class="col">
			<%
				count_opts = [[params[:count], params[:count]], [10, 10], [100, 100],[1000, 1000],["All", -1]].reject{|x| x[0].nil?}.map{|x| x.map(&:to_s)}.uniq
				tooltip = "Use /EXP/ to filter for regular expressions, use <, >, <=, >= in front of a number to filter for one sided ranges. Used ',' to query for multiple values at once."
			%>
			<%= label_tag "Limit to" %>: 
			<%= select_tag "count", options_for_select(count_opts, selected: (params[:count] || 10)) %>
		</div>
		<%filter_names.each_with_index do |f, i|%>
			<div class="col">
			<%= text_field_tag "_filter[#{f}]", (params[:_filter] || {})[f], title: tooltip, placeholder: f.to_s.humanize, style: "width: 120px;" %>
			</div>
		<%end%>
	</div>
<% end %>

app/views/home/_combobox.html.erb
<!-- <div class="field"> -->
<div class="ui-widget">
	<% if defined?label && label.to_s != "" then %>
		<label for="<%= boxid%>"><%= label%></label>
		<br />
	<% end %>
	<%= select_tag boxid, 
								options_for_select(selectoptions, selected: selected),
								{
									id: boxid, 
									name: boxid,
									onchange: onchange,
									"class" => "#{comboboxclass}",
									allowempty: (allowempty)?"1":"0",
									validonly: (validonly)?"1":"0"
								}
	
	%>
	
</div>
<!-- </div> -->

app/views/home/_help.html.erb
<% if defined?controller && defined?action && defined?template then %>
	<div class="helper">
		<span onclick="toggleHelp()" class='ui-icon ui-icon-help ui-corner-bl ui-state-hover' style='display:inline-block; margin: 0px 0px 3px -5px' title="Show help"></span>
	</div>
	<div class="helpertext">
		<div class="helpercontent">
			<%= render partial: template %>
		</div>
	</div> 
<% end %>

app/views/home/_help_index.html.erb
<p>
	<h2>Projects</h2> 
	The projects table shows you the projects you can access. Click on the name to reach the query page, or Show to view 
	project details, such as available samples and sample statistics. <br />
	The samples shows the samples that are part of the project. A green sample indicates, that the sample is ready to be 
	queried. Blue samples need to be annotated with a STATUS and TISSUE tag.
</p>

<p>
	<h2>Available Datasets</h2> 
	This shows a summary of the datasets you can access. The color coding helps to distinct the different elements.
</p>

<p>
	<h2>Navigation</h2> 
	Click on the elements in the navigatio menu to go to the overview of each ressource. You can access a single ressource 
	either from there or by following the sub menu.
</p>

<p>
	<h2>Your jobs</h2>
	Located on the bottom left of the sidebar you find a list of jobs that you submitted. Jobs are color coded by their state
	(DONE, ENQUEUED, RUNNING, FAILED) and can be access by following the link in the job list. 
</p>

app/views/home/_menu_item_with_subitems.html.erb
<li class="ui-menu-item">
	<a href=<%=url_for(controller: controller, action: "index", count: 100)%> class="ui-corner-all" role="menuitem">
		<span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span><%=caption%>
	</a>
	<ul class="menu ui-menu ui-widget ui-corner-all" style="display: none; font-size: 8pt;" role="menu" aria-expanded="false" aria-hidden="true">
		<% 
			if !defined?other_links then 
				other_links = {
					"Create new" => url_for(controller: controller, action: "new")
				}
			end
			if defined?links then
				other_links = other_links.merge((links || {}))
			end
		%>
		<% other_links.each do |linkname, url| %>
			<%= render(partial: "home/menu_item", locals: {
									caption: linkname,
									maxlength: 25,
									url: url
			})%>
		<% end %>
		
		<%="<hr />".html_safe if collection.size > 0 %>
		<% collection.each_with_index do |item, idx| %>
			<% 
				if local_assigns[:path_method].nil? then
					itemurl = url_for(controller: controller, action: "show", id: item.id)
				else 
				  itemurl = local_assigns[:path_method].call(item)
				end 
				itemcaption = item.send((local_assigns[:name_method] || :name))
		 	%>
			<%= render(partial: "home/menu_item", locals: {
									caption: itemcaption,
									url: itemurl,
									maxlength: 25,
									controller: controller,
									item: item,
									links: (defined?subitemlink)?(subitemlink):({})
									}
			)%>
		<% end %>
	</ul>
</li>

app/views/home/_navigation.html.erb
<ul class="menu ui-menu ui-widget ui-widget-content ui-corner-all" aria-activedescendant="ui-id-11" role="menu">
	<h2 style="margin: 3px 0px 4px 4px;"> Navigation </h2>
	<%= render(partial: "home/menu_item_with_subitems", locals: {
		controller:  :experiments,
		caption:     "Meta Projects",
		collection:  Organism.order("updated_at DESC").first(20),
		path_method: Proc.new() {|org| aqua_meta_path(user: current_user.id, organism: org.id)}
	}) %>
	<%= render(partial: "home/menu_item_with_subitems", locals: {
		controller:  :experiments,
		caption:     "Projects",
		collection:  current_user.experiments.where("experiments.id > 0").order("updated_at DESC").first(20),
		path_method: Proc.new() {|exp| aqua_experiment_path(exp)},
		subitemlink: {
			"Query Generator" => Proc.new() {|e| url_for(controller: :experiments, action: "query_generator", id: e.id)}
		}
	}) %>
	<%= render(partial: "home/menu_item_with_subitems", locals: {
		controller: :entity_groups,
		caption:    "Entity Groups",
		collection: current_user.visible(EntityGroup).order("updated_at DESC").first(20),
		links:      (!(current_user.is_admin? or current_user.is_data_manager?)) ? {} : {
			"Batch create" => url_for(controller: :entity_groups, action: "batch_create", count: 10)
		}
	}) %>
	<%= render(partial: "home/menu_item_with_subitems", locals: {
		controller:  :entities,
		caption:     "Entities",
		collection:  current_user.visible(Entity).order("updated_at DESC").first(20),
		subitemlink: {
			"Assign..." => Proc.new() {|item| entities_path(ids: item.id)}
		}
	}) %>
	<%= render(partial: "home/menu_item_with_subitems", locals: {
		controller:  :specimen_probes,
		caption:     "Specimen",
		collection:  current_user.visible(SpecimenProbe).order("updated_at DESC").first(20),
		subitemlink: {
			"Assign..." => Proc.new() {|item| specimen_probes_path(ids: item.id)}
		}
	}) %>
	<%= render(partial: "home/menu_item_with_subitems", locals: {
		controller: :samples,
		caption:    "Samples",
		collection: current_user.samples.order("updated_at DESC").first(20)
	}) %>
	<% if current_user.is_data_manager? then %>
		<%= render(partial: "home/menu_item_with_subitems", locals: {
			controller: :vcf_files,
			caption:    "VCF Files",
			collection: current_user.visible(VcfFile).nodata.limit(10).order('vcf_files.updated_at DESC'),
			links:      {
				"Batch upload" => url_for(controller: :vcf_files, action: "batch_submit")
			}
		}) %>
	<% end %>
	<%= render(partial: "home/menu_item_with_subitems", locals: {
		controller:  :tags,
		caption:     "Tags",
		collection:  Tag.all(:limit => 10, :order => 'updated_at DESC'),
		name_method: :value
	}) %>
	<%= render(partial: "home/menu_item_with_subitems", locals: {
		controller:  :generic_lists,
		caption:     "Panels",
		name_method: :title,
		collection:  current_user.generic_lists.order("updated_at DESC").first(10)
	}) %>
	<%= render(partial: "home/menu_item_with_subitems", locals: {
		controller:  :reports,
		caption:     "Reports",
		name_method: :name,
		collection:  current_user.visible(Report).order("updated_at DESC").first(10)
	}) %>
	<%= render(partial: "home/menu_item_with_subitems", locals: {
		controller:  :long_jobs,
		caption:     "Jobs",
		collection:  current_user.jobs.select([:"long_jobs.title", :"long_jobs.id"]).limit(20).order('updated_at DESC'),
		links:       {
				"Statistics" => url_for(controller: :long_jobs, action: "statistics")
		},
		name_method: :title,
		path_method: Proc.new() {|item| "long_jobs/#{item.id}"}
	}) %>
	<li>
		<%= link_to "My Profile", user_path(current_user) %>
	</li>
	<li>
		<%= link_to "Privacy", home_cookies_path %>
	</li>
</ul>
<br/>
<ul class="menu ui-menu ui-widget ui-widget-content ui-corner-all" aria-activedescendant="ui-id-11" role="menu">
	<h2 style="margin: 3px 0px 4px 4px;"> Tools </h2>
	<%= render(partial: "home/menu_item", locals: {
		caption: "PPI Network",
		url:     tools_ppi_network_path
	}) %>
	<li>
		<%= link_to "Query Interface", api_form_path %>
	</li>
</ul>

<br/>
<% if current_user().is_admin then %>
	<ul class="menu ui-menu ui-widget ui-widget-content ui-corner-all" aria-activedescendant="ui-id-11" role="menu">
		<h2 style="margin: 3px 0px 4px 4px;"> Management Section </h2>
		<!--
            <%= render(partial: "home/menu_item", locals: {
		caption: "Tasks",
		url:     "/"
	}) %>
        -->
		<%= render(partial: "home/menu_item_with_subitems", locals: {
			controller: :institutions,
			caption:    "Institutions",
			collection: Institution.all(:limit => 20, :order => 'updated_at DESC')
		}) %>
		<%= render(partial: "home/menu_item_with_subitems", locals: {
			controller:  :users,
			caption:     "Users",
			collection:  User.all(:limit => 25, :order => 'updated_at DESC'),
			links:       {
				"Access Control List" => url_for(controller: :users, action: "access_control_list")
			},
			subitemlink: {
				"ACL" => Proc.new() {|u| url_for(controller: :users, action: "access_control_list", ids: u.id, users: u.id)}
			}
		}) %>
		
		<%= render(partial: "home/menu_item_with_subitems", locals: {
			controller:  :generic_lists,
			caption:     "Panels",
			name_method: :title,
			collection:  GenericList.all(:limit => 20, :order => 'updated_at DESC')
		}) %>
		<li>
			<%= link_to "AQuA Information", home_aqua_path %>
		</li>
		<li>
			<%= link_to "Logs", home_show_log_path %>
		</li>
		
	</ul>
<% end %>

app/views/home/_table.csv.erb
<%= header.join("\t").gsub("#", "").html_safe %>
<% content.each_with_index.map do |rec, rowno|%>
<%= header.map{|colname|
	#colname = (rec[colname.to_s].nil?)?(colname.to_sym):(colname.to_s)
	#retarray = rec[colname]
	retarray = (rec[colname.to_s] || rec[colname.to_sym])
	retarray = [retarray] unless retarray.is_a?(Array)
	ret = retarray.map{|ret|
		if ret.is_a?(String) or ret.is_a?(Symbol) then
			ret = ret.to_s.gsub("\n", "\\n")
			ret = ret.gsub("'", "\"")
			# these symbols are troublesome if not handled correctly
#			ret = ret.gsub(">", "&gt;")
#			ret = ret.gsub("<", "&lt;")
			ret = strip_tags(ret)
			ret = "'#{ret}'"
		end
		ret
	}.join(",")
	ret.gsub!(/^#/, "\#")
	ret = ret.force_encoding('UTF-8')
	ret
}.join("\t").html_safe %>
<%end%>

app/views/home/about.html.erb
<h1>About</h1>
<p>The SNuPy platform supports genetic scientists to query and explore variation data.</p>

app/views/home/api_form.html.erb
<h1> Query Interface </h1>

<%= form_tag(api_form_path, method: 'post') do %>
    <p>
      <%= text_area_tag "query", params[:query], style: "width: 600px;height: 500px;" %>
    </p>
    <p>
      <%= label_tag "count", "Limit to" %>:
      <%= text_field_tag "count", (params[:count] || 5000) %>
    </p>
    <br/>
    <p>
      <%= submit_tag 'Submit', class: 'button' %>
    </p>
    <br>
    <%= render_table(@result, {
        title: "Query Result (#{params[:count].to_i})"
    }) %>
<% end %>
<% if @result.size > 0 %>
    <%= form_tag(api_path, method: 'post') do %>
        <%= hidden_field_tag("query", params[:query]) %>
        <p>
          <%= label_tag "format", "Format" %>:
          <%= select_tag "format", options_for_select(["csv", "text", "json"].map{|x| [x,x]}) %>
        </p>
        <p>
          <%= label_tag "sep", "Seperator" %>:
          <%= text_field_tag "sep", (params[:sep] || "\t"), placeholder: "Default: \t" %>
        </p>
        <p>
          <%= submit_tag 'Download this result (unlimited)', class: 'button' %>
        </p>
    <% end %>
<% end %>

app/views/home/citation.html.erb
<h1>Home#citation</h1>
<p>Find me in app/views/home/citation.html.erb</p>

app/views/home/index.html.erb
<div style="width: 750px">
	<div class="ui-widget" style="float: left; width: 100%;">
		<div class="homeheader" style="border:none;">
<!--			<p   style="top: 0px; margin-left: auto; margin-right: auto;text-align: center;"> -->
				<%=link_to "Projects", experiments_path %> |
				<%=link_to "Samples", samples_path %> |
				<%=link_to "Gene Panels", generic_lists_path %> |
				<%=link_to "Help", home_help_path %> |
				<%=link_to "About", home_about_path %>
				<% if File.exists?("public/snupy.tar.gz") %>
				| <%=link_to "Download", "snupy.tar.gz"%>
				<% end %>
			<!--			</p> -->
		</div>
	</div>

	<div style="margin-left: 10px; float: left; width: 100%;">
		<h4>
			Welcome <%= current_user.full_name %>
		</h4>
	</div>
	<br />
	
	<div style="margin-top: 10px; float: left; width: 750px">
		<% if @experiments.size > 0 %>
				<%= render_table(@experiments,
												 title: "Projects",
												 columns: %w(name contact),
												 column_order: %w(name contact),
												 selectbox: false
				){|rec, exp|
					smpls = exp.samples
					smpl_links = smpls.map{|smpl|
						if smpl.ready_to_query? then
							link_to "#{smpl.nickname}", sample_path(smpl), class: "success"
						else
							link_to "#{smpl.nickname}", sample_path(smpl), class: "running"						
						end
					}
					rec["samples"] = smpl_links.join(", ")
					rec[:name] = link_to exp.name, aqua_experiment_path(exp)
					rec
				}%>
			<br />
		<% end %>
		<% if @data_overview.size > 0 then%>
			<p>
				<%=render partial: "data_overview", locals: {
					data_overview: @data_overview
				}%>
			</p>
		<% end %>
		<% if @orphan_samples.size > 0 then %>
			<br />
			<%= render_table(@orphan_samples,
												 title: "Unlinked Samples (#{@orphan_samples.size}/#{@orphan_samples_total.to_i})",
												 columns: %w(name nickname contact),
												 column_order: %w(name nickname contact),
												 selectbox: false
				)%>
		<% end %>
	</div>
</div>