config/routes.rb
SnupyAgain::Application.routes.draw do
	
	resources :reports do
		member do
			get 'download'
		end
	end
	Report.subclasses.each do |k|
		resources k.name.underscore.pluralize, :controller => 'reports'
	end
	
	
	resources :entity_groups do
		collection do
			get 'batch_create'
			post 'batch_create'
			post 'show_dataset_summary'
			post 'assign_entity'
		end
	end
	
	resources :entities do
		collection do
			post 'assign_specimen_probe'
			post 'assign_entity_group'
			post 'assign_tags'
		end
		member do
			post 'show'
		end
	end
	
	resources :specimen_probes do
		collection do
			post 'assign_sample'
			post 'assign_entity'
			post 'assign_tags'
		end
	end
	
	resources :tags
	
	match 'long_jobs/clear_cache' => 'long_jobs#clear_cache', :as => "long_jobs_clear_cache", :via => "delete"
	match 'long_jobs/list' => 'long_jobs#list', :via => "get"
	match 'long_jobs/statistics' => 'long_jobs#statistics', :via => "get"
	match 'long_jobs/statistics' => 'long_jobs#statistics', :via => "post"
	match "long_jobs/:id/status" => 'long_jobs#status', :as => "long_job_status", :via => "get"
	match 'long_jobs/:id' => 'long_jobs#result', :as => "long_job_result", :via => "get"
	match 'long_jobs/:id/result' => 'long_jobs#result', :via => "get"
	match 'long_jobs/:id/kill' => 'long_jobs#destroy', :as => "long_job_kill", :via => "delete"
	match 'long_jobs' => 'long_jobs#index', :via => "get"
	
	
	
	resources :users do
		member do
			get 'longtask'
		end
		collection do
			get 'access_control_list'
		end
	end
	
	get "api", to: "home#api", as: "api"
	post "api", to: "home#api", as: "api"
	get "api_form", to: "home#api_form", as: "api_form"
	post "api_form", to: "home#api_form", as: "api_form"
	
	get "home/index"
	
	get "home/cookies"
	
	get "home/about"
	
	get "home/help"
	
	get "home/citation"
	
	get "home/aqua"
	get "home/show_log"
	post "home/show_log_details"
	post "home/destroy_log"
	
	get "aqua/query_collection/:qklass/:qname", to: "aqua#query_collection", as: "aqua_query_collection"
	get "aqua/query_details/:variation_id", to: "aqua#query_details", as: "aqua_query_details"
	post "aqua/query_details/:variation_id", to: "aqua#query_details", as: "aqua_query_details"
	
	get "tools/ppi_network"
	post "tools/ppi_network"
	get "tools/gene_details"
	post "tools/gene_details"
	
	resources :institutions, :generic_lists, :generic_gene_lists, :generic_region_lists
	resources :sample_tags
	resources :samples do
		collection do
			put 'refreshstats'
			get 'claimable'
			get 'refreshindex'
			post 'mass_destroy'
			post 'force_reload'
			post 'sample_similarity'
			post 'assign_specimen'
			post 'gender_coefficient'
			post 'refresh_stats'
		end
		member do
			get 'detail'
			post 'detail'
			put 'collectstats'
		end
	end
	
	resources :experiments do
		collection do
			post 'details'
			post 'more_details'
			get 'details'
			get 'more_details'
			post 'interactions'
			post 'interaction_details'
			post 'attribute_matrix'
			post 'panel_to_subject_matrix'
			post 'save_resultset'
		end
		member do
			get 'aqua'
			post 'aqua'
			get 'query_generator'
			post 'query_generator'
			get 'query', to: redirect('/experiments/%{id}/aqua')
		end
	end
	get 'experiments/aqua_meta/:user/:organism', controller: :experiments, action: :aqua_meta, as: :aqua_meta #=> "experiments#aqua_meta"
	
	get '/projects', to: redirect('/experiments')
	get '/projects/:id', to: redirect('/experiments/%{id}')
	
	resources :vcf_files do
		member do
			get 'annotate'
			get 'aqua_annotate'
			get 'download'
			post 'aqua_annotate_single'
		end
		collection do
			get 'batch_submit'
			post 'batch_submit'
			post 'create_sample_sheet'
			post 'download_sample_sheet'
			post 'assign_tags'
			post 'baf_plot'
			post 'mass_destroy'
			get 'baf_plot'
			get 'download_sample_sheet'
			get 'refreshindex'
		end
	end
	resources :vcf_file_varscans, :controller => "vcf_files", :type => "VcfFileVarscan"
	resources :vcf_file_excavators, :controller => "vcf_files", :type => "VcfFileExcavator"
	
	
	
	
	
	
	
	
	
	root :to => 'home#index'
	AquaRouter.load_aqua_routes

end

app/helpers/experiments_helper.rb
# == Description
# Helper Module
module ExperimentsHelper
	
	def get_from_param(*args)
		ret = params.dup()
		args.each do |key|
			return nil if ret[key].nil?
			ret = ret[key]
		end
		ret
	end
	
	# creates an array that represents one row of a VCF
	def create_vcf_result(aggregation_result, smpls)
		# group varcalls by region
		return ["NOT IMPLEMENTED YET"] if 1 == 1
		records = {}
		varcalls.each do |rec|
			key = "#{rec["regions.name"]}:#{rec["regions.start"]}"
			if records[key].nil? then
				if !(rec["variation_annotations.existing_variation"].to_s == "") then
					rsid = YAML.load(rec["variation_annotations.existing_variation"]).first
				else
					rsid = "."
				end
				records[key] = {
						chr: rec["regions.name"],
						pos: rec["regions.start"],
						id: rsid,
						ref: rec["alterations.ref"],
						alt: [],
						qual: [],
						filter: ".",
						info: [],
						format: "GT:AD:BAF:DP:GQ",
						samples: {}
				}
			end
			records[key][:alt] << rec["alterations.alt"]
			records[key][:qual] << rec["variation_calls.qual"]
			records[key][:info] << {
					genes: rec["genetic_elements.ensembl_gene_id"],
					features: rec["genetic_elements.ensembl_feature_id"],
					consequence: rec["consequences.consequence"],
					gmaf: (rec["variation_annotation.gmaf"] || ".")
			}
			records[key][:samples][rec["samples.nickname"]] = [
					rec["variation_calls.gt"],
					"#{rec["variation_calls.ref_reads"]},#{rec["variation_calls.alt_reads"]}",
					((rec["variation_calls.alt_reads"])/(rec["variation_calls.ref_reads"] + rec["variation_calls.alt_reads"] + (10**-32).to_f)).round(3),
					(rec["variation_calls.dp"] || 0),
					rec["variation_calls.gq"]
			].join(":")
		end
		## post process
		records.keys.each do |key|
			records[key][:alt] = records[key][:alt].uniq.join(",")
			records[key][:qual] = records[key][:qual].min
			# set info field to correct format
			tmp = records[key][:info].uniq.map{|gene_and_cons| [gene_and_cons[:features], gene_and_cons[:consequence]]}.uniq
			genes = records[key][:info].map{|gene_and_cons| gene_and_cons[:genes]}.uniq
			features = tmp.map{|g|g[0]}
			consequences = tmp.map{|g|g[1]}
			num_fatal = [consequences.select{|c| Consequence::FATAL.include?(c)}.size]
			gmaf = records[key][:info].map{|gene_and_cons| gene_and_cons[:gmaf]}.uniq
			records[key][:info] = {fatal: num_fatal, genes: genes, features: features, consequences: consequences, gmaf: gmaf}
		end

		ret = []
		records.each do |key, rec|
			ret << [
					rec[:chr],
					rec[:pos],
					rec[:id],
					rec[:ref],
					rec[:alt],
					rec[:qual],
					rec[:filter],
					rec[:info].map{|k,v|"#{k.upcase}=#{v.join(",")}"}.join(";"),
					rec[:format],
					smpls.map{|smpl|
						smplrec = rec[:samples][smpl.nickname]
						smplrec = ["0/0:0,0:0:0:0"] if smplrec.nil?
						smplrec
					}.join("\t")
			].join("\t")
		end
		ret.sort!{|x,y|
			x = x.split("\t")
			y = y.split("\t")
			d sprintf("%s:%d <=> %s:%d\n", x[0], x[1].to_i, y[0], y[1].to_i)
			chrx = x[0]
			chry = y[0]
			chrx = 23 if chrx == "X"
			chry = 23 if chry == "X"
			chrx = 24 if chrx == "Y"
			chry = 24 if chry == "Y"
			chrx = chrx.to_i
			chry = chry.to_i

			if chrx == chry then
				x[1].to_i <=> y[1].to_i
			else
				chrx <=> chry
			end
		}
		ret
	end

	def region_list_to_variants(ids)
		regions2search = ids
		regions2search = [regions2search] unless regions2search.is_a?(Array)
		@regions = []
		regions2search.each do |region|
			chr, start, stop = region.split(/[[:punct:]]/).first(3)
			@regions << Region.where("name = ? AND start BETWEEN ? AND ? AND stop BETWEEN ? AND ?",
									 chr, start, stop, start, stop)
		end
		@regions = @regions.flatten.uniq
		@variations = @regions.map{|r| r.overlapping_variations}.flatten.uniq
		@variations
	end
	
	def get_interactions_from_db(genes, threshold, organism_id, include_textmining = false)
		tmfilter = "(neighborhood > #{threshold} OR neighborhood_transferred > #{threshold} OR fusion > #{threshold} OR cooccurence > #{threshold} OR homology > #{threshold} OR coexpression > #{threshold} OR coexpression_transferred > #{threshold} OR experiments > #{threshold} OR experiments_transferred > #{threshold} OR `database` > #{threshold} OR database_transferred > #{threshold})"
		tmfilter = "" if include_textmining
		gene2string = Hash[genes.map{|g| [g, nil]}]
		string2input = {}
		StringProteinAliasName.where(alias: genes, organism_id: organism_id).each do |span|
			gene2string[span[:alias]] = span.stringdb_id
			string2input[span.stringdb_id] = span[:alias]
		end
		# get string proteins for input
		strings = StringProtein.where(stringdb_id: gene2string.values.flatten.uniq.reject(&:nil?))
		string_ids = strings.pluck("stringdb_id").uniq
		links = Aqua.scope_to_array (
									StringProteinLink.where("stringdb1_id IN (?) OR stringdb2_id IN (?)", string_ids, string_ids)
										.where("combined_score > #{threshold }")
										.where(tmfilter)
										.select([:stringdb1_id, :stringdb2_id, :combined_score])
									)
		link_nodes = links.map {|rec|
			[rec["stringdb1_id"], rec["stringdb2_id"], rec["combined_score"]]
		}.uniq
		# get string objects for all links so we can create a full set of nodes
		string_ids = links.map{|rec| [rec["stringdb1_id"], rec["stringdb2_id"]]}.flatten.uniq
		strings = StringProtein.where(stringdb_id: string_ids)
		strings2symbol = Hash[string_ids.map{|x| [x, x]}]
		res = Aqua.scope_to_array ( StringProteinAliasName.where(stringdb_id: string_ids, organism_id: organism_id).where("SOURCE LIKE '%GN'"))
		res.each{|rec|
			next if (not strings2symbol[rec["stringdb_id"]].nil?) and (not strings2symbol[rec["stringdb_id"]] == rec["stringdb_id"])
			strings2symbol[rec["stringdb_id"]] = rec["alias"]
		}
		nodes = strings.map{|n|
			{
				gene: n.stringdb_id,
				alias:  strings2symbol[n.stringdb_id],
				group: "none",
				url: ""
			}
		}
		
		edges = link_nodes.map{|from, to, score|
			{
				source: from,
				target: to,
				source_symbol: strings2symbol[from],
				target_symbol: strings2symbol[to],
				value: (score).to_i
			}
		}
		{
			nodes: nodes,
			edges: edges,
			input2string: gene2string,
			string2input: string2input,
			strings2symbol: strings2symbol
		}
		
		
	end
	
	
	def get_interaction_data(params)
		
		vcids = params[:ids].split(" | ")
		varids = VariationCall.where(id: vcids).pluck(:variation_id)
		
		@experiment = Experiment.find(params[:experiment])
		@organism = @experiment.organism
		interactions = {}
		string_partners = {}
		threshold = (params[:threshold] || 950).to_i
		list_network = {nodes: [], edges: [], input2string: {}, string2input: {}, strings2symbol: {}}
		if !params[:list].nil? and params[:list].to_i != 0 then
			@listgenes = GenericGeneList.find(params[:list]).genes
			list_network = get_interactions_from_db(@listgenes, threshold, @organism.id, params[:include_interaction_between_list_items] == "yes")
		else
			@listgenes = []
		end
		
		@selected_genes = {}
		Aqua.scope_to_array(Vep::Ensembl.where(variation_id: varids).select([:variation_id, :gene_id])).uniq.each do |rec|
			@selected_genes[rec["gene_id"]] ||= []
			@selected_genes[rec["gene_id"]] << rec["variation_id"]
			@selected_genes[rec["gene_id"]].uniq!
		end
		selected_network = get_interactions_from_db(@selected_genes.keys, threshold, @organism.id, params[:include_interaction_between_list_items] == "yes")
		
		
		network = {
			nodes: (list_network[:nodes] + selected_network[:nodes]).uniq,
			edges: (list_network[:edges] + selected_network[:edges]).uniq,
			input2string: (list_network[:input2string].merge selected_network[:input2string]),
			string2input: (list_network[:string2input].merge selected_network[:string2input]),
			strings2symbol: (list_network[:strings2symbol].merge selected_network[:strings2symbol])
		}
		
		## set the groups correctly
		network[:nodes].each do |n|
			n[:group] = "Interactions_partners" if not list_network[:string2input][n[:gene]].nil?
			n[:group] = "Target_genes" if not selected_network[:string2input][n[:gene]].nil?
			n[:group] = "both" if not selected_network[:string2input][n[:gene]].nil? and not list_network[:string2input][n[:gene]].nil?
			if not selected_network[:string2input][n[:gene]].nil? then
				vars = @selected_genes[selected_network[:string2input][n[:gene]]]
				n[:url] = "VARIDS: #{(vars || []).join(" | ")}"
			end
		end
		
		# clear empty nodes and those which have no intersting connection
		node_count = Hash.new(0)
		network[:edges].each do |e|
			# node_count[e[:source]] += 1
			node_count[e[:target]] += 1
		end
		
		network[:nodes].select!{|n|
			node_count[n[:gene]] > 0 and (node_count[n[:gene]] > 1 or n[:group] != "none")
		}
		node_present = Hash[network[:nodes].map{|n| [n[:gene], true]}]
		node_present.default = false
		network[:edges].select!{|e|
			node_present[e[:source]] && node_present[e[:target]]
		}
		
		url_template = interaction_details_experiments_path
		
		labels = Hash[network[:edges].map{|n|
			[n[:gene], n[:alias]]
		}]
		missing = []
		
		###set colors
		colors = {
			Target_genes: "#6495ED",
			Interactions_partners:"#E9967A",
			both:"#6A5ACD",
			none: "#AAAAAA"
		}
		colors.default = "#000000"
		
		width, height = params[:dimension].to_s.gsub(" ", "").split(",")[0..1]
		width = 1024 if width.nil?
		height = (width.to_i * 0.75).round(0) if height.nil?
		return {
			edges: network[:edges],
			nodes: network[:nodes],
			url_template: url_template,
			colors: colors,
			groups: [],
			labels: labels,
			width: width,
			height: height,
			experiment: params[:experiment],
			missing: missing
		}
	end
	
	def get_interaction_data_thais(params)
		
		alias_table = "stringdb.protein_alias"
		alias_stringdb_id = "stringdb"
		link_table = "stringdb.protein_links"
		link_experiment = "experimental"
		alias_table = "string_protein_alias"
		alias_stringdb_id = "stringdb_id"
		link_table = "string_protein_links"
		link_experiment = "experiments"
		
		if params[:ids].all?{|id| id =~ /[0-9XYM]+[:punct:][0-9]+[:punct:][0-9]+/} then

app/views/experiments/_details.csv.erb
<%=render_table(@details,
				title: "Details from #{@samples.size} of your samples",
				format: "csv",
				select_type: :none
)%>

app/views/experiments/_details.json.erb
<%= (details || []).map{|rec|
	rec.update(rec){|k, v, v1|
		strip_tags(v.to_s)
	}
}.to_json.html_safe %>

app/views/experiments/_help_edit.html.erb
<%= render partial: "#{params[:controller]}/help_new" %>

app/views/experiments/_interaction_details.html.erb
<div id="node_details">
	<p>
		more information:
		<%if(!params[:url].to_s.empty?)%>
			<%= link_to  "#{gene_symbol}", "genecards.org/cgi-bin/carddisp.pl?gene=#{gene_symbol}",  :target => '_blank' %>
		<%else%>
			Gene could not be found at GeneCards
		<%end%>
	</p>

	<p>
		Protein: <%=gene_details[:gene]%><br>
		Gene: <%=gene_details[:alias]%><br>
		Group: <%=gene_details[:group]%><br>
	</p>
	
	<%=render_table(
			details,
				  title: "Details for " + gene_symbol + " (max 200 records)",
				  id: "gene_details_#{Time.now.to_i}",
			selectbox: false,
			groupby: ["variations.id", "sample_name"]
	)%>
</div>

app/views/experiments/_more_details.html.erb
<%= render_table(@tbl, title: "More details",
				 column_order: %w(samples.name samples.nickname variation_calls.sample_id samples.specimen_probe_id samples.entity_id samples.entity_group_id is.control disease
				 samples.vcf_sample_name samples.contact
				 variation_calls.gt variation_calls.ref_reads variation_calls.alt_reads variation_calls.dp variation_calls.gq variation_calls.filter)
){ |rec, obj|
	rec["variation_calls.sample_id"] = link_to(rec["variation_calls.sample_id"], sample_path(rec["variation_calls.sample_id"])) unless rec["variation_calls.sample_id"].nil?
	rec["samples.specimen_probe_id"] = link_to(rec["samples.specimen_probe_id"], specimen_probe_path(rec["samples.specimen_probe_id"])) unless rec["samples.specimen_probe_id"].nil?
	rec["samples.entity_id"]         = link_to(rec["samples.entity_id"], entity_path(rec["samples.entity_id"])) unless rec["samples.entity_id"].nil?
	rec["samples.entity_group_id"]   = link_to(rec["samples.entity_group_id"], entity_group_path(rec["samples.entity_group_id"])) unless rec["samples.entity_group_id"].nil?
rec
}%>

app/views/experiments/aqua.html.erb
<h1> AQuA Query <%=@experiment.title%> (<%=@experiment.name%>)</h1>

<p>
	<%= link_to 'Edit/Add/Remove Samples', edit_experiment_path(@experiment.id) %> 
	<%= link_to 'Details', experiment_path(@experiment.id) %>
</p>

<% if @samples.size > 0 then %>
	<%= field_set_tag "Create Query" do %>
		<%= form_for :experiment, url: aqua_experiment_path(@experiment), namespace: :aqua, method: :post, action: :aqua do |f| %>
			<div style="float: left; width: 100%;">
				<%= field_set_tag "Samples" do %>
					<%=render_table(
													(@samples), 
													title: "",
													id: "samples",
													selected: (@selected_samples || Sample.where("1 = 0")).pluck("samples.id"),
													record_color: {
															"Group" => :factor,
															"Entity" => :factor,
															"Specimen" => :factor,
															"Sample" => :factor,
															"Entity.tags" => :factor,
															"Specimen.tags" => :factor,
															"Sample.tags" => :factor,
															"VcfFile.tags" => :factor
													},
													collapsecell: 180,
													column_order: %w(SampleID Group Entity Specimen Sample VcfFile nickname patient gender sample_type Entity.tags Specimen.tags Sample.tags VcfFile.tags Show Edit ignorefilter status notes contact vcf_sample_name .*),
													actions: {
														"Similarity" => sample_similarity_samples_path()
													}
					){|rec, s|
						rec["SampleID"] = link_to "#{s.id}", sample_path(s)
						rec["Group"] = (!s.entity_group.nil?)?(link_to "#{s.entity_group.name}", entity_group_path(s.entity_group)):("NA")
						rec["Entity"] = (!s.entity.nil?)?(link_to "#{s.entity.name}", entity_path(s.entity)):("NA")
						rec["Specimen"] = (!s.specimen_probe.nil?)?(link_to "#{s.specimen_probe.name}", specimen_probe_path(s.specimen_probe)):("NA")
						rec["Sample"] = link_to "#{s.name}", sample_path(s)
						rec["VcfFile"] = link_to "#{s.vcf_file_nodata.name}", vcf_file_path(s.vcf_file_nodata)
						rec["Edit"] = link_to "Edit #{s.nickname}", edit_sample_path(s)
						rec["Entity.tags"] = (!s.entity.nil?)?(s.entity.tags.join(" | ")):("NA")
						rec["Specimen.tags"] = (!s.specimen_probe.nil?)?(s.specimen_probe.tags.join(" | ")):("NA")
						rec["Sample.tags"] = (!s.nil?)?(s.tags.join(" | ")):("NA")
						rec["VcfFile.tags"] = (!s.vcf_file_nodata.nil?)?(s.vcf_file_nodata.tags.join(" | ")):("NA")

						#rec["tags"] = s.sample_tags.map{|st| "#{st.tag_name}:#{st.tag_value}"}.uniq.join("<br>")
						rec
					}%>
				<% end %>
				<div>
						<p>
							<%= submit_tag 'Select Samples', class: 'button' %>
							<%= text_field_tag "tag_formula", params[:tag_formula].to_s, placeholder: "(INIT & somatic & male) + (REMI & 'primary immune deficiency' & female)", size: 134 %>
						</p>
						<% if !@tag_formula_message.nil? %>
								<div class="success" style="display: inline-block">
									<%= @tag_formula_message %>
								</div>
						<% end %>
						<% if !@tag_formula_error.nil? %>
							<div class="fail" style="display: inline-block">
								<%= @tag_formula_error %>
							</div>
						<% end %>
				</div>
			</div>
			<div style="float: left; width: 750px;">
				<%= field_set_tag "Filters" do %>
					<%= render partial: "experiments/aqua/queries/queries", locals: {queries: @queries} %>
				<% end %>
			</div>
			<div style="float: left; width: 550px;">
				<%= field_set_tag "Group" do %>
					<%= render partial: "experiments/aqua/aggregations/aggregations", locals: {aggregations: @group_aggregations} %>
				<% end %>
				<br>
				<%= field_set_tag "Attributes" do %>
					<%= render partial: "experiments/aqua/aggregations/aggregations", locals: {aggregations: @attr_aggregations} %>
				<% end %>
			</div>
			<br style="clear: both;" />
			<div style="float: left;">
				<%= select_tag "format", 
											options_for_select([
												["HTML", "html"], 
												["CSV", "csv"],
												["VCF", "vcf"], 
												["Excel", "xls"],
												["JSON", "json"],
												["Aqua JSON", "aqua"]
											], 
											selected: "html"),
											onChange: "if($(this).val() != 'html'){
												tmp = this;
												if (!confirm('Be aware that downloading results can result in inconsistency between the underlying variation data and your downloaded copy.')){
													$(this).val('html');
												}
											};"
				%>
			</div>
			<br style="clear: both;" />
			<div class="actions" id="commit_action_section" style="float: left;">
				<%= submit_tag "OK" %>
				<%= select_tag "commit_action", 
											options_for_select([
												["Query", "query"], 
												["Submit new", "newjob"],
												["Load", "load"], 
												["Delete", "delete"]
											], 
											selected: (params[:commit_action] || "query")),
											onchange: "changeAquaSubmitOptions(this.value)"
				%>
				<%= text_field_tag "jobname_text", "", style: "display:none" %>
				<%= select_tag "jobname_select", options_from_collection_for_select(@long_jobs, "id", "title", selected: (@long_job.nil?)?"":@long_job.id), include_blank: false, style: "display:none" %>
			</div>
		<% end %>
	<% end %>
<% else %>
You will be able to create queries when at least one sample was successfully imported.
<% end %>

<br style="clear: both;" />
<% if (@result || []).size > 0 then %>
		<p>
			<%
				aqua_actions = {}
				Aqua.route_paths.each do |description, url|
					if url.nil?
						Aqua.log_error("#{description} does not have associated route to it")
						next
					else
						aqua_actions[description] = {url: url, params: {experiment_id: @experiment.id, samples: params[:samples], queries: params["queries"].to_yaml, aggregations: params["aggregations"].to_yaml}}
					end
				end
				aqua_actions = {
					#"Save" => "save me",
					"Look-up variations in other samples" => {url: details_experiments_path(experiment: @experiment.id), params: {samples: params[:samples], tags: 'yes', queries: params["queries"].to_yaml, aggregations: params["aggregations"].to_yaml}},
					"Show interactions"                   => {url: interactions_experiments_path(experiment: @experiment.id), params: {samples: params[:samples], queries: params["queries"].to_yaml, aggregations: params["aggregations"].to_yaml}},
					"Attribute matrix"                    => {url: attribute_matrix_experiments_path(experiment: @experiment.id), params: {samples: params[:samples], queries: params["queries"].to_yaml, aggregations: params["aggregations"].to_yaml}},
					"Gene panel to subject"               => {url: panel_to_subject_matrix_experiments_path(experiment: @experiment.id), params: {samples: params[:samples], queries: params["queries"].to_yaml, aggregations: params["aggregations"].to_yaml}},
					"Save selected records"               => {url: save_resultset_experiments_path(experiment: @experiment.id), params: {samples: params[:samples], queries: params["queries"].to_yaml, aggregations: params["aggregations"].to_yaml}},
				}.merge(aqua_actions)
			%>
			<%=render_table(@result, 
											title: "Query Results",
											id: "query_result",
											idcol: "variation_calls.id",
											base_model: VariationCall,
											details_path: aqua_query_details_path(variation_id: ":id"),
											detail_params: {tools: "all", group: true, experiment: @experiment.id, samples: (@samples || []).map(&:id)},
											colors: @column2color,
											record_colors: @column2recordcolor,
											actions: aqua_actions
											)%>
		</p>
	<br />
	<% if Rails.env == "development" %>
		RESULT: <%=simple_format(@result.pretty_inspect.gsub("  ", "&nbsp;&nbsp;").gsub("<", "&lt;").gsub(">", "&gt;").html_safe) %>
	<% end %>
<% else %>
	No results available.
<% end %>

<% if Rails.env == "development" %>
	<%= field_set_tag "debugparams" do %>
		<%= simple_format(params.pretty_inspect.gsub("  ", "&nbsp;&nbsp;").gsub("<", "&lt;").gsub(">", "&gt;").html_safe) %>
		<br style="clear: both" />
	<% end %>
	<%= field_set_tag "aquaqueriedebug" do %>
		<%= simple_format(@queries.pretty_inspect.gsub("  ", "&nbsp;&nbsp;").gsub("<", "&lt;").gsub(">", "&gt;").html_safe) %>
		<br style="clear: both" />
	<% end %>
	<%= field_set_tag "allaquaqueriedebug" do %>
		<%= simple_format(Query.descendants.pretty_inspect.gsub("  ", "&nbsp;&nbsp;").gsub("<", "&lt;").gsub(">", "&gt;").html_safe) %>
		<br style="clear: both" />
	<% end %>
	<%= field_set_tag "QParams debug" do %>
		<%= simple_format(@qparams.pretty_inspect.gsub("  ", "&nbsp;&nbsp;").gsub("<", "&lt;").gsub(">", "&gt;").html_safe) %>
		<br style="clear: both" />
	<% end %>
<% end %>

app/views/experiments/index.html.erb
<h1>Projects</h1>

<%=render_table(@experiments.sort{|x,y| x.name<=>y.name}, 
								title: "",
								path_method: "experiment_list_path",
								column_order: %w(name title description contact Users) + ["number of samples", "institution name", ".*", "show"]
								){|rec, exp|
	# rec["number of samples"] = exp.samples.length
	rec[:name] = link_to exp.name, aqua_experiment_path(exp)
	rec["institution name"] = (exp.institution || Institution.new).name
	rec["Users"] = exp.users.map{|u| link_to u.name, user_path(u)}.join(", ")
	rec[:edit] = link_to 'Edit', edit_experiment_path(rec[:id])
	rec[:show] = link_to 'Show', experiment_path(rec[:id])
	rec[:destroy] = link_to 'Destroy', exp, method: :delete, data: { confirm: 'Are you sure?' }
	rec.delete(:institution)
	rec.delete(:updated_at)
	rec.delete(:institution_id)
	rec
}%>

<br />

<%= link_to 'New Project', new_experiment_path %>